name: Release helm chart files

on:
  push:
    branches:
      - master
    paths:
      - "helm/chaos-mesh/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "cwen0"
          git config user.email "cwen0@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.2
        with:
          charts_dir: "/helm"
          charts_rep: "https://cwen0.github.io/chaos-mesh"
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
